name: multiste-wizard

services:
  db:
    image: postgres:17.0
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '8001:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
